# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD:q1w2e3r4t5
    volumes:
       - ./src:/files/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 80:8080
